name: tf_efficientnet_b2_ns_Adam
sync_dist: True # Use when training with multiple gpu
arch:
  _target_: src.networks.EfficientNetB3DSPlus
  n_class: 2
  model_name: tf_efficientnet_b2_ns
monitor: val/loss
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0003
  weight_decay: 1.0e-05
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 20
  gamma: 0.1
