name: tf_efficientnet_b4_ns_SGD
sync_dist: True # Use when training with multiple gpu
arch:
  _target_: src.networks.EfficientNetB3DSPlus
  n_class: 2
  model_name: tf_efficientnet_b4_ns
monitor: "val/loss"
optimizer:
  _target_: torch.optim.SGD
  lr: 1e-3
  weight_decay: 1e-5
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 20
  gamma: 0.1
