name: tf_efficientnet_b7_ns
sync_dist: True # Use when training with multiple gpu
arch:
  _target_: src.networks.EfficientNetB3DSPlus
  n_class: 2
  model_name: tf_efficientnet_b7_ns
  pretrained: True
monitor: "val/loss"
loss:
  _target_: torch.nn.CrossEntropyLoss
  label_smoothing: 0.0
optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 1e-5
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 5
  gamma: 0.2