name: tf_efficientnet_b6_ns
sync_dist: True # Use when training with multiple gpu
arch:
  _target_: src.networks.EfficientNetB3DSPlus
  n_class: 2
  model_name: tf_efficientnet_b6_ns
monitor: val/loss
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  weight_decay: 1.0e-5
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 1
  eta_min: 1.0e-6
