name: baseline-tf_efficientnet_b4_ns
state: train # train/test/debug
seed: 42

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

logging:
  root: ./logs

dataset:
  train_list: ${work_dir}/data/train/train.csv
  val_list: ${work_dir}/data/train/val.csv
  data_dir: ${work_dir}/data
  crop_size: 512
  batch_size: 16
  num_workers: 4
  pin_memory: True

model:
  sync_dist: True # Use when training with multiple gpu
  n_class: 2

  model_name: tf_efficientnet_b4_ns

  optimizer:
    lr: 3e-4
    weight_decay: 1e-5
  lr_scheduler:
    step_size: 20
    gamma: 0.1

trainer:
  # GPU related
  precision: 16
  accelerator: gpu
  devices: -1
  num_nodes: 1
  strategy: null
  benchmark: True
  sync_batchnorm: False

  # Training related
  # max_steps: 100000
  max_epochs: 10
  # limit_train_batches: 1.0
  # gradient_clip_val: 0.1 # gradient clipping max norm
  # gradient_clip_algorithm: "norm"

# Logging, progress bar
refresh_rate: 10

model_ckpt:
  dirpath: ckpts/
  filename: "checkpoint-epoch{epoch}-step{step}-val_acc{val/acc:.3f}-val_loss{val/loss:.3f}"
  monitor: val/loss
  save_last: True
  save_top_k: 1
  mode: min
  auto_insert_metric_name: False

ddp_plugin:
  # These two args only work with accelerator = "ddp"
  find_unused_params: True # FIXME: Find out why turn this to False will fail to launch the training
  fp16_hook: True
  static_graph: False

hydra:
  run:
    dir: ./outputs/${name}/${now:%Y-%m-%d-%H-%M-%S}
